### ISSUE TITLE
Cannot build pylikwid with likwid 5.4

### ISSUE THREAD

**Issue by connorjward** [RRZE-HPC/pylikwid#19]
Having just installed likwid 5.4 from source, running
```
$ python setup.py build_ext -I /usr/local/include/ -L /usr/local/lib/ -R /usr/local/lib/
```
crashes with the following error:
```
$ python setup.py build_ext -I /usr/local/include/ -L /usr/local/lib/ -R /usr/local/lib/
/home/connor/Code/firedrake1/pylikwid/setup.py:13: SyntaxWarning: invalid escape sequence '\d'
  ver_regex = re.compile(b"so.(\d+)[.]*(\d*)")
/home/connor/Code/firedrake1/pylikwid/setup.py:91: SyntaxWarning: invalid escape sequence '\.'
  m = re.match("lib(.*)\.so", os.path.basename(library))
Searching for LIKWID installation in all folders in $PATH, $LIKWID_PREFIX and /usr/local
If you can use LIKWID on the CLI but it is not found, use LIKWID_PREFIX=$(realpath $(dirname $(which likwid-topology))/..)
Using LIKWID prefix directory at /usr/local
Using LIKWID include directory at /usr/local/include
Using LIKWID library directory at /usr/local/lib
Using LIKWID library named /usr/local/lib/liblikwid.so.5.4
/usr/local /usr/local/lib likwid /usr/local/include
pylikwid.c:4:10: fatal error: bstrlib.h: No such file or directory
    4 | #include <bstrlib.h>
      |          ^~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

which I believe is due to https://github.com/RRZE-HPC/likwid/issues/661. However, if I simply copy `bstrlib.h` into `/usr/local/include` then I get a different error:

```
/home/connor/Code/firedrake1/pylikwid/setup.py:13: SyntaxWarning: invalid escape sequence '\d'
  ver_regex = re.compile(b"so.(\d+)[.]*(\d*)")
/home/connor/Code/firedrake1/pylikwid/setup.py:91: SyntaxWarning: invalid escape sequence '\.'
  m = re.match("lib(.*)\.so", os.path.basename(library))
Searching for LIKWID installation in all folders in $PATH, $LIKWID_PREFIX and /usr/local
If you can use LIKWID on the CLI but it is not found, use LIKWID_PREFIX=$(realpath $(dirname $(which likwid-topology))/..)
Using LIKWID prefix directory at /usr/local
Using LIKWID include directory at /usr/local/include
Using LIKWID library directory at /usr/local/lib
Using LIKWID library named /usr/local/lib/liblikwid.so.5.4
/usr/local /usr/local/lib likwid /usr/local/include
pylikwid.c: In function ‘likwid_initaffinity’:
pylikwid.c:703:47: error: request for member ‘data’ in something not a structure or union
  703 |         PyDict_SetItem(a, PYSTR("tag"), PYSTR(bdata(affinity->domains[i].tag)));
      |                                               ^~~~~
pylikwid.c:7:40: note: in definition of macro ‘PYSTR’
    7 | #define PYSTR(str) (Py_BuildValue("s", str))
      |                                        ^~~
pylikwid.c:703:47: error: request for member ‘data’ in something not a structure or union
  703 |         PyDict_SetItem(a, PYSTR("tag"), PYSTR(bdata(affinity->domains[i].tag)));
      |                                               ^~~~~
pylikwid.c:7:40: note: in definition of macro ‘PYSTR’
    7 | #define PYSTR(str) (Py_BuildValue("s", str))
      |                                        ^~~
error: command '/usr/bin/gcc' failed with exit code 1
```

Any help would be appreciated.

I had some success installing older likwid versions, but they did not support my processor.

**Comment by connorjward** [comment]
In case it is useful.

From https://github.com/RRZE-HPC/likwid/issues/661:

> But the fix is more likely required on the pylikwid side. It assumes that the affinity group tag is a bstring and thus uses bdata(). This was changed in 5.4+ to be a character array.

**Comment by OoJJBoO** [comment]
Hi @connorjward, in case it is still relevant to you: Since I ran into the same problem, I just created a [pull request](https://github.com/RRZE-HPC/pylikwid/pull/20) which should fix this issue :)

**Comment by TomTheBear** [comment]
PR got merged. You should be able to build it again from source

**Comment by connorjward** [comment]
It now builds with 5.4. Thank you!
